# Generated by Django 5.2.2 on 2025-09-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestStories',
        ),
    ]
