# Generated by Django 5.2.2 on 2025-09-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_delete_teststories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFDocument',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
