# Generated by Django 5.2.2 on 2025-09-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_comment_edit_token_comment_ip_address_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentresponse',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='commentresponse',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
