# Generated by Django 5.2.2 on 2025-09-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_alter_commentresponse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentresponse',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentresponse',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='commentresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentResponse',
        ),
    ]
